# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task2_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QGridLayout

import pyqtgraph as pg


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1627, 1022)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(True)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(5, 5, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)

        ############ original graph #########
                     
        self.original_signal_graph = pg.PlotWidget(self.centralwidget)
        self.original_signal_graph.setMouseEnabled(x=True, y=True) 
        #self.original_signal_graph.setEnabled(False)
        #self.original_signal_graph.graph = pg.PlotWidget(self.original_signal_graph)
        #self.original_signal_graph.graph.setMouseEnabled(x=True, y=True)
        #Self.original_signal_graph.grid_graph_3 = QGridLayout()
        #self.original_signal_graph.setLayout(self.original_signal_graph.grid_graph_3)
        #self.original_signal_graph.grid_graph_3.addWidget(self.original_signal_graph.graph, 0, 0, 1, 1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.original_signal_graph.sizePolicy().hasHeightForWidth())
        self.original_signal_graph.setSizePolicy(sizePolicy)
        self.original_signal_graph.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.original_signal_graph.setMouseTracking(True)
        self.original_signal_graph.setTabletTracking(True)
        self.original_signal_graph.setAcceptDrops(True)
        self.original_signal_graph.setAutoFillBackground(False)
        self.original_signal_graph.setBackground((27, 27, 27))
        self.original_signal_graph.setStyleSheet("background-color: rgb(27, 27, 27);\n"
                "border-radius: 25px;\n"
                "buttoon-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
                "widget-shadow: 2px 2px 5px rgb(0, 0, 0);")
        self.original_signal_graph.setObjectName("original_signal_graph")
        self.horizontalLayout_4.addWidget(self.original_signal_graph, stretch = 1)

        ####### difference plot #######

        # self.difference_signal_graph = QtWidgets.QWidget(self.centralwidget)
        self.difference_signal_graph = pg.PlotWidget(self.centralwidget)
        self.difference_signal_graph.setMouseEnabled(x=True, y=True)
        self.difference_signal_graph.setStyleSheet("background-color: rgb(27, 27, 27);\n"
                "border-radius: 25px;\n"
                "buttoon-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
                "widget-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
                "")
        self.difference_signal_graph.setObjectName("difference_signal_graph")
        self.horizontalLayout_4.addWidget(self.difference_signal_graph, stretch = 1)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 5, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 550, -1)
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fs_label = QtWidgets.QLabel(self.centralwidget)
        self.fs_label.setStyleSheet("color: rgb(255, 255, 255);\n"
                        "font: italic 10pt \"Georgia\";\n"
                        "")
        self.fs_label.setObjectName("fs_label")
        self.horizontalLayout_2.addWidget(self.fs_label)
        self.fs_horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.fs_horizontalSlider.setStyleSheet("QSlider::groove:horizontal {\n"
                "        height: 8px;\n"
                "        background: #A9DED8;\n"
                "        border-radius: 4px;\n"
                "    }\n"
                "    QSlider::handle:horizontal {\n"
                "        background: #498480;\n"
                "        border: 2px solid #A9DED8;\n"
                "        width: 20px;\n"
                "        height: 20px;\n"
                "        margin: -6px 0;\n"
                "        border-radius: 10px;\n"
                "    }\n"
                "    QSlider::sub-page:horizontal {\n"
                "        background: #498480;\n"
                "        border-radius: 4px;\n"
                "    }\n"
                "    QSlider::add-page:horizontal {\n"
                "        background: #A9DED8;\n"
                "        border-radius: 4px;\n"
                "    }")
        self.fs_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.fs_horizontalSlider.setObjectName("fs_horizontalSlider")
        self.horizontalLayout_2.addWidget(self.fs_horizontalSlider)
        self.snr_label = QtWidgets.QLabel(self.centralwidget)
        self.snr_label.setStyleSheet("color: rgb(255, 255, 255);\n"
                        "font: italic 10pt \"Georgia\";\n"
                        "")
        self.snr_label.setObjectName("snr_label")
        self.horizontalLayout_2.addWidget(self.snr_label)
        self.snr_horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.snr_horizontalSlider.setStyleSheet("QSlider::groove:horizontal {\n"
                        "        height: 8px;\n"
                        "        background: #A9DED8;\n"
                        "        border-radius: 4px;\n"
                        "    }\n"
                        "    QSlider::handle:horizontal {\n"
                        "        background: #498480;\n"
                        "        border: 2px solid #A9DED8;\n"
                        "        width: 20px;\n"
                        "        height: 20px;\n"
                        "        margin: -6px 0;\n"
                        "        border-radius: 10px;\n"
                        "    }\n"
                        "    QSlider::sub-page:horizontal {\n"
                        "        background: #498480;\n"
                        "        border-radius: 4px;\n"
                        "    }\n"
                        "    QSlider::add-page:horizontal {\n"
                        "        background: #A9DED8;\n"
                        "        border-radius: 4px;\n"
                        "    }")
        self.snr_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.snr_horizontalSlider.setObjectName("snr_horizontalSlider")
        self.horizontalLayout_2.addWidget(self.snr_horizontalSlider)
        self.methods_comboBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.methods_comboBox.sizePolicy().hasHeightForWidth())
        self.methods_comboBox.setSizePolicy(sizePolicy)
        self.methods_comboBox.setMinimumSize(QtCore.QSize(100, 35))
        self.methods_comboBox.setStyleSheet("QComboBox {\n"
                        "    background-color: #1C1C1C;  /* Background color */\n"
                        "    color: white;  /* Text color */\n"
                        "    border: 1px solid #1C1C1C;\n"
                        "    border-radius: 15px;  /* Rounded corners */\n"
                        "    padding: 5px;\n"
                        "    font-size: 14px;\n"
                        "}\n"
                        "\n"
                        "QComboBox::drop-down {\n"
                        "    border: none;\n"
                        "    border-radius: 10px;  /* Rounded corners for the arrow box */\n"
                        "    background-color: #1C1C1C;\n"
                        "    width: 30px;\n"
                        "}\n"
                        "\n"
                        "QComboBox::down-arrow {\n"
                        "    width: 15px;\n"
                        "    height: 15px;\n"
                        "    color: white;  /* Arrow color */\n"
                        "}\n"
                        "\n"
                        "QComboBox QAbstractItemView {\n"
                        "    border: 1px solid #1C1C1C;\n"
                        "    selection-background-color: #1C1C1C;  /* Selected item background color */\n"
                        "    background-color: #1C1C1C;  /* Dropdown background color */\n"
                        "    color: white;\n"
                        "    border-radius: 10px;\n"
                        "}\n"
                        "")
        self.methods_comboBox.setObjectName("methods_comboBox")
        self.methods_comboBox.addItem("")
        self.methods_comboBox.addItem("Linear")
        self.methods_comboBox.addItem("Whittaker–Shannon")
        self.methods_comboBox.addItem("Cubic Spline")
        self.horizontalLayout_2.addWidget(self.methods_comboBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(5, 5, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 7, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(15, -1, 15, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.original_signal_label = QtWidgets.QLabel(self.centralwidget)
        self.original_signal_label.setStyleSheet("color: rgb(255, 255, 255);\n"
                        "font: italic 11pt \"Georgia\";\n"
                        "")
        self.original_signal_label.setTextFormat(QtCore.Qt.PlainText)
        self.original_signal_label.setObjectName("original_signal_label")
        self.horizontalLayout.addWidget(self.original_signal_label)
        spacerItem3 = QtWidgets.QSpacerItem(500, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.difference_signal_label = QtWidgets.QLabel(self.centralwidget)
        self.difference_signal_label.setStyleSheet("color: rgb(255, 255, 255);\n"
                        "font: italic 11pt \"Georgia\";\n"
                        "")
        self.difference_signal_label.setTextFormat(QtCore.Qt.PlainText)
        self.difference_signal_label.setObjectName("difference_signal_label")
        self.horizontalLayout.addWidget(self.difference_signal_label)
        spacerItem4 = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.mixer_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.mixer_button.sizePolicy().hasHeightForWidth())
        self.mixer_button.setSizePolicy(sizePolicy)
        self.mixer_button.setMinimumSize(QtCore.QSize(80, 30))
        self.mixer_button.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.mixer_button.setMouseTracking(True)
        self.mixer_button.setStyleSheet("font: italic 10pt \"Georgia\";\n"
                        "background-color: rgb(169, 222, 216);\n"
                        "buttoon-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
                        "border-radius: 10px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Desktop/icons/icons8-zoom-out-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.mixer_button.setIcon(icon)
        self.mixer_button.setObjectName("mixer_button")
        self.horizontalLayout.addWidget(self.mixer_button)
        self.open_file_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_file_button.sizePolicy().hasHeightForWidth())
        self.open_file_button.setSizePolicy(sizePolicy)
        self.open_file_button.setMinimumSize(QtCore.QSize(100, 30))
        self.open_file_button.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.open_file_button.setMouseTracking(True)
        self.open_file_button.setStyleSheet("font: italic 10pt \"Georgia\";\n"
                "font: 12pt \"Georgia\";\n"
                "background-color: rgb(169, 222, 216);\n"
                "buttoon-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
                "border-radius: 10px;")
        self.open_file_button.setObjectName("open_file_button")
        self.horizontalLayout.addWidget(self.open_file_button)
        self.gridLayout_4.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.mixer_label = QtWidgets.QLabel(self.centralwidget)
        self.mixer_label.setStyleSheet("color: rgb(255, 255, 255);\n"
                "font: italic 11pt \"Georgia\";\n"
                "")
        self.mixer_label.setObjectName("mixer_label")
        self.horizontalLayout_8.addWidget(self.mixer_label)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.tests_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.tests_comboBox.setStyleSheet("QComboBox {\n"
                "    background-color: #1C1C1C;  /* Background color */\n"
                "    color: white;  /* Text color */\n"
                "    border: 1px solid #1C1C1C;\n"
                "    border-radius: 15px;  /* Rounded corners */\n"
                "    padding: 5px;\n"
                "    font-size: 14px;\n"
                "}\n"
                "\n"
                "QComboBox::drop-down {\n"
                "    border: none;\n"
                "    border-radius: 10px;  /* Rounded corners for the arrow box */\n"
                "    background-color: #1C1C1C;\n"
                "    width: 30px;\n"
                "}\n"
                "\n"
                "QComboBox::down-arrow {\n"
                "    width: 15px;\n"
                "    height: 15px;\n"
                "    color: white;  /* Arrow color */\n"
                "}\n"
                "\n"
                "QComboBox QAbstractItemView {\n"
                "    border: 1px solid #1C1C1C;\n"
                "    selection-background-color: #1C1C1C;  /* Selected item background color */\n"
                "    background-color: #1C1C1C;  /* Dropdown background color */\n"
                "    color: white;\n"
                "    border-radius: 10px;\n"
                "}")
        self.tests_comboBox.setObjectName("tests_comboBox")
        self.tests_comboBox.addItem("")
        self.horizontalLayout_8.addWidget(self.tests_comboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem6)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(300, 0))
        self.tableWidget.setStyleSheet("QTabelWidget {\n"
                "    background-color: rgb(0, 0, 0);\n"
                "    background-color : back;\n"
                "    color: rgb(255, 255, 255);\n"
                "    border : none;\n"
                "    font-family: \"Arial\";\n"
                "    font-size : 14px;\n"
                "}\n"
                "\n"
                "QTabelWidget :: item {\n"
                "borde-bottom: 1px solid gray;\n"
                "}\n"
                "\n"
                "QTabelWidget :: item : selected {\n"
                "background-color : darckgray;\n"
                "}\n"
                "\n"
                "QHeaderView :: section{\n"
                "border : none\n"
                "}")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.mixed_signal_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.mixed_signal_label.sizePolicy().hasHeightForWidth())
        self.mixed_signal_label.setSizePolicy(sizePolicy)
        self.mixed_signal_label.setMinimumSize(QtCore.QSize(150, 30))
        self.mixed_signal_label.setStyleSheet("color: rgb(255, 255, 255);\n"
                "font: italic 10pt \"Georgia\";\n"
                "")
        self.mixed_signal_label.setObjectName("mixed_signal_label")
        self.verticalLayout_2.addWidget(self.mixed_signal_label)
        self.mixed_signal_graph = QtWidgets.QWidget(self.centralwidget)
        self.mixed_signal_graph.setStyleSheet("background-color: rgb(27, 27, 27);\n"
                "border-radius: 25px;\n"
                "buttoon-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
                "widget-shadow: 2px 2px 5px rgb(0, 0, 0);")
        self.mixed_signal_graph.setObjectName("mixed_signal_graph")
        self.verticalLayout_2.addWidget(self.mixed_signal_graph)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.apply_button_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(90)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apply_button_2.sizePolicy().hasHeightForWidth())
        self.apply_button_2.setSizePolicy(sizePolicy)
        self.apply_button_2.setMinimumSize(QtCore.QSize(80, 30))
        self.apply_button_2.setStyleSheet("font: italic 10pt \"Georgia\";\n"
                        "font: 12pt \"Georgia\";\n"
                        "background-color: rgb(169, 222, 216);\n"
                        "buttoon-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
                        "border-radius: 10px;")
        self.apply_button_2.setObjectName("apply_button_2")
        self.horizontalLayout_5.addWidget(self.apply_button_2)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 5, 1, 5, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(15, -1, 15, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.reconstructed_signal_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reconstructed_signal_label.sizePolicy().hasHeightForWidth())
        self.reconstructed_signal_label.setSizePolicy(sizePolicy)
        self.reconstructed_signal_label.setMinimumSize(QtCore.QSize(0, 30))
        self.reconstructed_signal_label.setStyleSheet("color: rgb(255, 255, 255);\n"
                "font: italic 10pt \"Georgia\";\n"
                "")
        self.reconstructed_signal_label.setObjectName("reconstructed_signal_label")
        self.horizontalLayout_7.addWidget(self.reconstructed_signal_label)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem9)
        self.frequancy_domain_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frequancy_domain_label.sizePolicy().hasHeightForWidth())
        self.frequancy_domain_label.setSizePolicy(sizePolicy)
        self.frequancy_domain_label.setMinimumSize(QtCore.QSize(0, 30))
        self.frequancy_domain_label.setStyleSheet("color: rgb(255, 255, 255);\n"
                "font: italic 10pt \"Georgia\";\n"
                "")
        self.frequancy_domain_label.setObjectName("frequancy_domain_label")
        self.horizontalLayout_7.addWidget(self.frequancy_domain_label)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem10)
        self.gridLayout_4.addLayout(self.horizontalLayout_7, 8, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem11 = QtWidgets.QSpacerItem(5, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem11)
        self.title_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_label.sizePolicy().hasHeightForWidth())
        self.title_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.title_label.setFont(font)
        self.title_label.setStyleSheet("color: rgb(255, 255, 255);\n"
                "font: 75 20pt \"Microsoft PhagsPa\";")
        self.title_label.setTextFormat(QtCore.Qt.PlainText)
        self.title_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(15, -1, 275, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.actual_radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.actual_radioButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: italic 10pt \"Georgia\";\n"
"")
        self.actual_radioButton.setObjectName("actual_radioButton")
        self.horizontalLayout_3.addWidget(self.actual_radioButton)
        self.normalized_radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.normalized_radioButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: italic 10pt \"Georgia\";\n"
"")
        self.normalized_radioButton.setObjectName("normalized_radioButton")
        self.horizontalLayout_3.addWidget(self.normalized_radioButton)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem12)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 6, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem13 = QtWidgets.QSpacerItem(5, 5, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem13)

        ##############       reconstruction graph      #############

        self.reconstructed_signal_graph = pg.PlotWidget(self.centralwidget)
        self.reconstructed_signal_graph.setMouseEnabled(x=True, y=True)
        # self.reconstructed_signal_graph = QtWidgets.QWidget(self.centralwidget)
        # self.reconstructed_signal_graph.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reconstructed_signal_graph.sizePolicy().hasHeightForWidth())
        self.reconstructed_signal_graph.setSizePolicy(sizePolicy)
        self.reconstructed_signal_graph.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reconstructed_signal_graph.setMouseTracking(True)
        self.reconstructed_signal_graph.setTabletTracking(True)
        self.reconstructed_signal_graph.setAcceptDrops(True)
        self.reconstructed_signal_graph.setAutoFillBackground(False)
        self.reconstructed_signal_graph.setStyleSheet("background-color: rgb(27, 27, 27);\n"
                "border-radius: 25px;\n"
                "buttoon-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
                "widget-shadow: 2px 2px 5px rgb(0, 0, 0);")
        self.reconstructed_signal_graph.setObjectName("reconstructed_signal_graph")
        self.horizontalLayout_6.addWidget(self.reconstructed_signal_graph, stretch = 1)

        ######### frequency graph ##########

        # self.frequancy_domain_graph = QtWidgets.QWidget(self.centralwidget)
        self.frequancy_domain_graph = pg.PlotWidget(self.centralwidget)
        self.frequancy_domain_graph.setMouseEnabled(x=True, y=True)
        self.frequancy_domain_graph.setStyleSheet("background-color: rgb(27, 27, 27);\n"
                "border-radius: 25px;\n"
                "buttoon-shadow: 2px 2px 5px rgb(0, 0, 0);\n"
                "widget-shadow: 2px 2px 5px rgb(0, 0, 0);")
        self.frequancy_domain_graph.setObjectName("frequancy_domain_graph")
        self.horizontalLayout_6.addWidget(self.frequancy_domain_graph, stretch = 1)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 9, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.fs_label.setText(_translate("MainWindow", "FS"))
        self.snr_label.setText(_translate("MainWindow", "SNR"))
        self.methods_comboBox.setItemText(0, _translate("MainWindow", "Method"))
        self.original_signal_label.setText(_translate("MainWindow", "Original Signal"))
        self.difference_signal_label.setText(_translate("MainWindow", "Difference Signal"))
        self.mixer_button.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.mixer_button.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">)pen</span></p></body></html>"))
        self.mixer_button.setText(_translate("MainWindow", "Mixer"))
        self.open_file_button.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.open_file_button.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">)pen</span></p></body></html>"))
        self.open_file_button.setText(_translate("MainWindow", "Open File"))
        self.mixer_label.setText(_translate("MainWindow", "Mixer"))
        self.tests_comboBox.setItemText(0, _translate("MainWindow", "Tests"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "frequancy"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "amplitude"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "phase"))
        self.mixed_signal_label.setText(_translate("MainWindow", "Mixed Signal"))
        self.apply_button_2.setText(_translate("MainWindow", "Apply"))
        self.reconstructed_signal_label.setText(_translate("MainWindow", "Reconstructed Signal"))
        self.frequancy_domain_label.setText(_translate("MainWindow", "Frequancy Domain"))
        self.title_label.setText(_translate("MainWindow", "Sampling Theory Studio"))
        self.actual_radioButton.setText(_translate("MainWindow", "Actual"))
        self.normalized_radioButton.setText(_translate("MainWindow", "Normalized"))
